---
# https://github.com/jonashackt/molecule-ansible-docker-vagrant#project-structure
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: geerlingguy/centos7
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning,ignore:.*Unknown ssh.*:UserWarning"
  lint:
    name: flake8
